##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
#/home/pcelars5/repositories/OrganicFood
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pcelars5/public_html
    - /bin/cp -R * $DEPLOYPATH
    #    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css
