##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
#/home/pcelars5/repositories/OrganicFood
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pcelars5/public_html/OrganicFood
    - /bin/cp -R * $DEPLOYPATH

