---
deployment:
  tasks:
    # Folder gdje je Laravel projekat (izvan public_html)
    - export PROJECTPATH=/home/pcelars5/OrganicFood
    # Folder web servera (public_html)
    - export DEPLOYPATH=/home/pcelars5/public_html

    # Kopiraj samo sadržaj public/ u public_html
    - /bin/cp -R $PROJECTPATH/public/* $DEPLOYPATH/


