##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
#/home/pcelars5/repositories/OrganicFood
#https://pobjeda.com:2083/cpsess9724415117/frontend/jupiter/filemanager/index.html?dir=%2Fhome%2Fpobjeda%2Fpublic_html%2Fnorme.pobjeda.com
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pcelars5/public_html
    - /bin/cp -R * $DEPLOYPATH
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/css

