<?php

namespace App\Mcp\Tools;

use Illuminate\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;

class OrderTool extends Tool
{
    /**
     * The tool's description.
     */
    protected string $description = 'Legacy placeholder tool. Prefer using the dedicated order tools: list_orders, get_order, create_order, update_order_status.';

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
         // Ovdje ide logika, npr. dohvat iz baze
        $orderId = $request['order_id'];
        // $order = Order::find($orderId);
        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, \Illuminate\JsonSchema\JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            //
        ];
    }
}
